import { expect, test } from '@playwright/test';

test('全RS事業・接続有無・年度・検索・選択・MOF往復', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/budget-flow');
  await page.getByRole('button', { name: 'RS 事業', exact: true }).click();
  const table = page.getByRole('table', { name: 'RS事業一覧', exact: true });
  await expect(table.locator('tbody tr')).toHaveCount(5794);
  await page.getByLabel('MOFとの接続', { exact: true }).selectOption('unlinked');
  await expect(table.locator('tbody tr')).toHaveCount(1257);
  await table.locator('tbody button').nth(1).click();
  const name = await table.locator('tbody button[aria-pressed=true]').innerText();
  await expect(page.getByRole('region', { name: 'RS事業詳細', exact: true }).getByRole('heading', { name, exact: true })).toBeVisible();
  await expect(page.getByText('選択した予算年度にMOF接続はありません。')).toBeVisible();
  await page.getByLabel('MOFとの接続', { exact: true }).selectOption('linked');
  await expect(table.locator('tbody tr')).toHaveCount(4537);
  await page.getByLabel('表示金額・接続の予算年度').selectOption('2025');
  await expect(table.locator('tbody tr')).toHaveCount(4851);
  await page.getByRole('button', { name: 'リセット', exact: true }).click();
  await page.getByRole('searchbox', { name: 'RS事業を検索', exact: true }).fill('デジタル庁');
  await expect(table.locator('tbody tr').first()).toBeVisible();
  const selected = await table.locator('tbody button').first().innerText();
  await table.locator('tbody button').first().click();
  const detail = page.getByRole('region', { name: 'RS事業詳細', exact: true });
  await expect(detail.getByRole('heading', { name: selected, exact: true })).toBeVisible();
  await expect(detail.getByRole('button', { name: /→$/ }).first()).toBeVisible();
  await page.screenshot({ path: '/tmp/budget-flow-rs-desktop.png', fullPage: true });
  const mofName = (await detail.getByRole('button', { name: /→$/ }).first().innerText()).replace(' →', '');
  await detail.getByRole('button', { name: /→$/ }).first().click();
  await expect(page.getByRole('button', { name: 'MOF 項', exact: true })).toHaveAttribute('aria-pressed','true');
  await expect(page.getByRole('heading', { name: mofName, exact: true })).toBeVisible();
  await expect(page.getByLabel('予算年度 · fiscalYear')).toHaveValue('2025');
  await page.getByRole('button', { name: 'Identity / RS', exact: true }).click();
  await page.getByText(/レビュー年度 2025 → fiscalYear 2025/).click();
  const rsLink = page.getByRole('button', { name: `${selected} →`, exact: true });
  await expect(rsLink).toBeVisible();
  await rsLink.click();
  await expect(detail.getByRole('heading', { name: selected, exact: true })).toBeVisible();
  await expect(table.locator('tbody tr')).toHaveCount(5794);
  await page.getByLabel('RSレビュー年度').selectOption('2024');
  await expect(table.locator('tbody tr')).toHaveCount(5664);
  await expect(page.getByLabel('表示金額・接続の予算年度')).toHaveValue('2024');
  await page.getByLabel('表示金額・接続の予算年度').selectOption('2021');
  await expect(table.locator('tbody tr')).toHaveCount(5664);
  await expect(table.locator('tbody tr').first()).toContainText('照合データなし');
  expect(errors).toEqual([]);
});

test('RSの検索・金額範囲・幅調整・モバイル・読込失敗からの復帰', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto('/budget-flow');
  await page.getByRole('button', { name: 'RS 事業', exact: true }).click();
  const table = page.getByRole('table', { name: 'RS事業一覧', exact: true });
  await expect(table.locator('tbody tr')).toHaveCount(5794);
  await page.getByRole('searchbox', { name: 'RS事業を検索', exact: true }).fill('存在しない|デジタル庁');
  await expect(table.locator('tbody tr')).toHaveCount(0);
  await page.getByRole('button', { name: 'RS事業を検索の正規表現', exact: true }).click();
  await expect(table.locator('tbody tr').first()).toBeVisible();
  await page.getByRole('searchbox', { name: 'RS事業を検索', exact: true }).fill('[');
  await expect(page.locator('main').getByRole('alert')).toContainText('正規表現が正しくありません');
  await page.getByRole('button', { name: 'リセット', exact: true }).click();
  await page.getByRole('textbox', { name: 'RS金額の下限（円）' }).fill('0');
  await page.getByRole('textbox', { name: 'RS金額の上限（円）' }).fill('0');
  await expect(table.locator('tbody tr').first()).toBeVisible();
  const amounts = await table.locator('tbody tr td:last-child').allTextContents();
  expect(amounts.every(s => s === '0 円')).toBe(true);
  for (const name of ['フィルタとRS事業一覧の幅','RS事業一覧と詳細の幅','事業名の列幅']) {
    const handle = page.getByRole('separator',{name,exact:true});
    const before = Number(await handle.getAttribute('aria-valuenow'));
    await handle.focus(); await page.keyboard.press('ArrowRight');
    expect(Number(await handle.getAttribute('aria-valuenow'))).not.toBe(before);
  }
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/budget-flow-rs-mobile.png', fullPage: true });
  await page.route('**/budget-flow-v2/rs/2024.json.gz',route => route.fulfill({status:503,body:'unavailable'}));
  await page.getByLabel('RSレビュー年度').selectOption('2024');
  await expect(page.locator('main').getByRole('alert')).toContainText('503');
  await page.unroute('**/budget-flow-v2/rs/2024.json.gz');
  await page.getByRole('button',{name:'RSデータを再読み込み',exact:true}).click();
  await expect(table.locator('tbody tr').first()).toBeVisible();
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
});

test('詳細シャード失敗から復帰し視点切替で検索と選択を保持する', async ({ page }) => {
  await page.route('**/budget-flow-v2/rs/2025/*.json.gz', route => route.fulfill({status:503,body:'unavailable'}));
  await page.goto('/budget-flow');
  await page.getByRole('button', { name: 'RS 事業', exact: true }).click();
  const detail = page.getByRole('region', { name: 'RS事業詳細', exact: true });
  await expect(detail.getByRole('alert')).toContainText('503');
  await page.unroute('**/budget-flow-v2/rs/2025/*.json.gz');
  await detail.getByRole('button', { name: 'RS詳細を再読み込み' }).click();
  await expect(detail.getByRole('heading', { name: '予算・執行 · FY 2024' })).toBeVisible();
  await page.getByRole('searchbox', { name: 'RS事業を検索', exact: true }).fill('デジタル庁');
  const table = page.getByRole('table', { name: 'RS事業一覧', exact: true });
  await table.locator('tbody button').nth(1).click();
  const selected = await table.locator('tbody button[aria-pressed=true]').innerText();
  await page.getByRole('button', { name: 'MOF 項', exact: true }).click();
  await page.getByRole('button', { name: 'RS 事業', exact: true }).click();
  await expect(page.getByRole('searchbox', { name: 'RS事業を検索', exact: true })).toHaveValue('デジタル庁');
  await expect(detail.getByRole('heading', { name: selected, exact: true })).toBeVisible();
});
