import { expect, test } from '@playwright/test';

test('実データの検索、原典、年度、同一コードの別項を確認する', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/budget-flow');
  await expect(page.getByRole('heading', { name: 'Budget Event タイムライン' })).toBeVisible();
  await page.getByRole('searchbox', { name: '項・所管を検索', exact: true }).fill('科学技術イノベーション創造推進費');
  await expect(page.getByRole('heading', { name: '科学技術イノベーション創造推進費', exact: true })).toBeVisible();
  const evidence = page.getByRole('region', { name: 'Evidence / 原典' });
  await evidence.locator('summary').first().click();
  await expect(evidence.getByText('raw record:', { exact: false }).first()).toBeVisible();
  await expect(evidence.getByText('SHA-256:', { exact: false }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Identity / RS', exact: true }).click();
  await expect(page.getByText('canonical ID:', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: '現行モデルとの差分', exact: true }).click();
  await expect(page.getByRole('table').last()).toBeVisible();
  await page.getByLabel(/^会計:/).click();
  await page.getByRole('checkbox', { name: '一般会計', exact: true }).uncheck();
  await page.getByRole('checkbox', { name: '特別会計', exact: true }).check();
  await page.getByRole('searchbox', { name: '項・所管を検索', exact: true }).fill('復興');
  await expect(page.getByRole('button', { name: /^復興債費/ }).first()).toBeVisible();
  await expect(page.getByRole('button', { name: /^復興庁共通費/ }).first()).toBeVisible();
  await page.getByLabel('予算年度 · fiscalYear').selectOption('2025');
  await page.getByLabel('モード').selectOption('settlement');
  await expect(page.getByText('このフルデータには2025年度のMOF決算イベントがありません。')).toBeVisible();
  await page.getByRole('button', { name: '条件をリセット' }).click();
  await page.getByRole('searchbox', { name: '項・所管を検索', exact: true }).fill('科学技術イノベーション創造推進費');
  await page.getByRole('button', { name: 'Budget Events', exact: true }).click();
  await expect(page.getByRole('button', { name: /当初予算・提出案/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /当初予算・成立/ })).toBeVisible();
  expect(errors).toEqual([]);
});

test('狭い画面と読込エラーを扱う', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/budget-flow');
  await expect(page.getByRole('heading', { name: 'Budget Event タイムライン' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.route('**/budget-flow-v2/2025.json.gz', route => route.fulfill({ status: 503, body: 'unavailable' }));
  await page.getByLabel('予算年度 · fiscalYear').selectOption('2025');
  await expect(page.locator('main').getByRole('alert')).toContainText('503');
  await page.unroute('**/budget-flow-v2/2025.json.gz');
  await page.getByRole('button', { name: '再読み込み' }).click();
  await expect(page.getByRole('heading', { name: 'Budget Event タイムライン' })).toBeVisible();
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
});


test('複数選択・候補検索・正規表現・ペイン幅を操作する', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto('/budget-flow');
  await expect(page.getByRole('heading', { name: 'Budget Event タイムライン' })).toBeVisible();
  await page.getByLabel(/^会計:/).click();
  await page.getByRole('checkbox', { name: '特別会計', exact: true }).check();
  await expect(page.getByRole('checkbox', { name: '一般会計', exact: true })).toBeChecked();
  await page.getByLabel(/^所管・組織:/).click();
  await page.getByRole('searchbox', { name: '所管・組織の候補を検索', exact: true }).fill('デジタル庁');
  await page.getByRole('checkbox', { name: 'デジタル庁', exact: true }).check();
  const table = page.getByRole('table', { name: '項一覧', exact: true });
  await expect(table.locator('tbody').getByRole('button').first()).toBeVisible();
  const keyword = page.getByRole('searchbox', { name: '項・所管を検索', exact: true });
  await keyword.fill('存在しない文字列|デジタル');
  await expect(table.locator('tbody').getByRole('button')).toHaveCount(0);
  await page.getByRole('button', { name: '項・所管を検索の正規表現', exact: true }).click();
  await expect(table.locator('tbody').getByRole('button').first()).toBeVisible();
  await keyword.fill('[');
  await expect(page.locator('main').getByRole('alert')).toContainText('正規表現が正しくありません');
  await page.getByRole('button', { name: 'リセット', exact: true }).click();
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '項・所管を検索の正規表現', exact: true })).toHaveAttribute('aria-pressed', 'false');
  for (const name of ['フィルタと項一覧の幅', '項一覧と詳細の幅']) {
    const handle = page.getByRole('separator', { name });
    const before = Number(await handle.getAttribute('aria-valuenow'));
    const box = (await handle.boundingBox())!;
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 30, box.y + box.height / 2);
    await page.mouse.up();
    expect(Number(await handle.getAttribute('aria-valuenow'))).not.toBe(before);
    await handle.focus();
    await page.keyboard.press('ArrowLeft');
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const count = await page.getByRole('region', { name: '項一覧ペイン' }).getByRole('status').innerText();
  await expect(table.locator('tbody tr')).toHaveCount(Number(count.split(' 件')[0].replaceAll(',', '')));
  await page.setViewportSize({ width: 1120, height: 900 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.getByRole('checkbox', { name: '一般会計', exact: true }).check();
  await page.getByRole('checkbox', { name: 'デジタル庁', exact: true }).check();
  await expect(table.getByText('読込中…', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: '/tmp/budget-flow-desktop.png', fullPage: true });
});


test('一覧ソート、列幅、クリア位置、金額範囲を操作する', async ({ page }) => {
  await page.setViewportSize({ width: 1800, height: 1000 });
  await page.goto('/budget-flow');
  await expect(page.getByRole('heading', { name: 'Budget Event タイムライン' })).toBeVisible();
  await page.getByLabel(/^会計:/).click();
  await expect(page.getByRole('searchbox', { name: '会計の候補を検索', exact: true })).toHaveCount(0);
  const keyword = page.getByRole('searchbox', { name: '項・所管を検索', exact: true });
  await keyword.fill('デジタル庁');
  const clear = page.getByRole('button', { name: '項・所管を検索をクリア', exact: true });
  const regex = page.getByRole('button', { name: '項・所管を検索の正規表現', exact: true });
  expect((await clear.boundingBox())!.x).toBeGreaterThan((await regex.boundingBox())!.x);
  await clear.click();
  await expect(keyword).toHaveValue('');
  await expect(keyword).toBeFocused();
  await keyword.fill('デジタル庁');
  const table = page.getByRole('table', { name: '項一覧', exact: true });
  await expect(table.locator('tbody tr')).toHaveCount(4);
  await expect(table.getByText('読込中…', { exact: true })).toHaveCount(0);
  const selected = await table.locator('tbody button[aria-pressed=true]').innerText();
  const sort = table.getByRole('button', { name: '当初予算額（円）で並べ替え' });
  const amountCells = () => table.locator('tbody tr td:last-child').allTextContents();
  await sort.click();
  await expect(sort.locator('..')).toHaveAttribute('aria-sort', 'ascending');
  expect(await amountCells()).toEqual(['1,033,584,000 円', '15,046,161,000 円', '480,327,293,000 円', '—']);
  await sort.click();
  expect(await amountCells()).toEqual(['480,327,293,000 円', '15,046,161,000 円', '1,033,584,000 円', '—']);
  await expect(table.locator('tbody button[aria-pressed=true]')).toHaveText(selected);
  const handle = page.getByRole('separator', { name: '項名の列幅', exact: true });
  const before = (await table.locator('th').first().boundingBox())!.width;
  const box = (await handle.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 80, box.y + box.height / 2);
  await page.mouse.up();
  expect((await table.locator('th').first().boundingBox())!.width).toBeGreaterThan(before + 60);
  await expect(sort.locator('..')).toHaveAttribute('aria-sort', 'descending');
  await handle.focus();
  await page.keyboard.press('ArrowLeft');
  const lower = page.getByRole('textbox', { name: '金額の下限（円）' });
  const upper = page.getByRole('textbox', { name: '金額の上限（円）' });
  await lower.fill('0');
  await upper.fill('2,000,000,000');
  await expect(table.locator('tbody tr')).toHaveCount(1);
  await expect(table.locator('tbody')).toContainText('デジタル社会形成推進費');
  await page.screenshot({ path: '/tmp/budget-flow-followup.png', fullPage: true });
  await lower.fill('3000000000');
  await expect(page.locator('main').getByRole('alert')).toContainText('下限は上限以下');
  await lower.fill('0');
  await upper.fill('');
  await expect(table.locator('tbody tr')).toHaveCount(3);
  await page.getByRole('button', { name: 'リセット', exact: true }).click();
  await expect(lower).toHaveValue('');
  await expect(upper).toHaveValue('');
  await expect(page.locator('main').getByRole('alert')).toHaveCount(0);
});
